from fastapi import APIRouter, Depends, HTTPException, status
from uuid import UUID
from typing import List
from sqlalchemy.ext.asyncio import AsyncSession
from app.core.db import get_db
from app.schemas.chat import ChatCreate, ChatRead, ChatResponse
from app.schemas.logs import MessageCreate, MessageRead
from app.services.chat import ChatService
from app.models.api_response import StandardResponse
from app.core.dependencies import get_chat_svc
import logging

logger = logging.getLogger(__name__)

router = APIRouter(prefix="/chats", tags=["chats"])

@router.post("/", response_model=StandardResponse[ChatRead])
async def create_chat(
    chat_create: ChatCreate,
    db: AsyncSession = Depends(get_db),
    chat_svc: ChatService = Depends(get_chat_svc),
):
    """Creates a new chat id to input user query from uploaded document id

    Args:
        chat_create (ChatCreate): Schema to store questions in db
        db (AsyncSession, optional): Database instance
        chat_svc (ChatService, optional): Chat service object.

    Returns:
        chat JSON: Document id, name & metadata for reference
    """
    try:
        chat_data = await chat_svc.create_chat(db, chat_create)
        return StandardResponse(
            status=201,
            message="Chat ID created successfully",
            data=chat_data
        )
    except ValueError as e:
        raise HTTPException(
            status_code=status.HTTP_400_BAD_REQUEST,
            detail=str(e),
        )


@router.get("/", response_model=StandardResponse[List[ChatRead]])
async def get_chats(
    db: AsyncSession = Depends(get_db),
    chat_svc: ChatService = Depends(get_chat_svc),
):
    """List past chat conversation ids

    Args:
        db (AsyncSession, optional): Database instance.
        chat_svc (ChatService, optional): Chat service object.

    Returns:
        A JSON array of chat ids 
    """
    get_chat_list = await chat_svc.find_all_chats(db)
    return StandardResponse(
        status=200,
        message="Chat ID retrieved successfully",
        data=get_chat_list
    )


@router.post("/{chat_id}/messages", response_model=StandardResponse[ChatResponse])
async def send_message(
    chat_id: UUID,
    payload: MessageCreate,
    db: AsyncSession = Depends(get_db),
    chat_svc: ChatService = Depends(get_chat_svc),
):
    """Generates answers, references and confidence score of a question

    Args:
        chat_id (UUID): Unique chat id for current conversation
        payload (MessageCreate): Schema to store generated messages 
        db (AsyncSession, optional): Database instance.
        chat_svc (ChatService, optional): Chat service object.

    Raises:
        HTTPException: Incomplete argument parsing, fails to generate AI response
        HTTPException: Invalid chat error
        HTTPException: Unexpected LLM or runtime errors

    Returns:
        answer: Content generated by LLM for a given question
        References: Source citation in the pdf for the answers
        Confidence: A confidence score for the answer
    """
    try:
        message = await chat_svc.send_message(
            session=db,
            chat_id=chat_id,
            message_create=payload,
        )
        
        if not message:
            raise HTTPException(
                status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
                detail="Failed to generate AI response",
            )
        send_message_data=ChatResponse(
            answer=message.content,
            references=message.sources,
            confidence=message.confidence,
        )
        return StandardResponse(
            status=201,
            message="LLM response generated",
            data=send_message_data
        )

    except ValueError as e:
        logger.warning(f"Chat validation error: {e}")
        raise HTTPException(
            status_code=status.HTTP_400_BAD_REQUEST,
            detail=str(e),
        )

    except HTTPException:
        raise

    except Exception as e:
        # Unexpected errors (LLM, DB, vector store, etc.)
        logger.exception("Unexpected error while generating chat response")
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail="An unexpected error occurred while processing your request",
        )


@router.get("/{chat_id}/messages", response_model=StandardResponse[List[MessageRead]])
async def get_messages(
    chat_id: UUID,
    db: AsyncSession = Depends(get_db),
    chat_svc: ChatService = Depends(get_chat_svc),
):
    """Retrieve past chat conversation for a given chat id

    Args:
        chat_id (UUID): Unique chat id
        db (AsyncSession, optional): Database instance.
        chat_svc (ChatService, optional): Chat service object.

    Returns:
        A JSON object representing chat ids. 
    """
    get_message_id=await chat_svc.find_messages(db, chat_id)
    return StandardResponse(
        status=200,
        message=f"Conversation for chat id {chat_id} retrieved",
        data=get_message_id
    )
