from sqlalchemy.ext.asyncio import AsyncSession
from sqlalchemy import select
from uuid import UUID
from typing import Sequence, Optional, List
from app.models.logs import Message, SenderType

class MessageRepository:
    """Storage logic for message database
    """
    async def create(
        self,
        db: AsyncSession,
        chat_id: UUID,
        content: str,
        sender_type: SenderType,
        sources: Optional[List[str]] = None,
        confidence: Optional[float] = None,
    ) -> Message:
        """Data retrieval for Logs

        Args:
            db (AsyncSession): Database instance.
            chat_id (UUID): Unique chat id
            content (str): Response generated by LLM
            sender_type (SenderType): HUMAN or AI
            sources (Optional[List[str]], optional): Source citation of the document
            confidence (Optional[float], optional): Confidence score.

        Returns:
            Message: Database model that stores logs
        """
        msg = Message(
            chat_id=chat_id,
            content=content,
            sender_type=sender_type,
            sources=sources,
            confidence=confidence
        )
        db.add(msg)
        await db.flush()
        return msg

    async def save_many(
        self,
        db: AsyncSession,
        messages: Sequence[Message],
    ):
        """Stores multiple logs in a single operation"""
        db.add_all(messages)
        await db.flush()

    async def find_by_chat_id(
        self,
        db: AsyncSession,
        chat_id: UUID,
    ) -> Sequence[Message]:
        """Retrieve a specific log by it's chat id

        Args:
            db (AsyncSession): Database instance
            chat_id (UUID): Unique chat id

        Returns:
            Sequence[Message]: A JSON array of message log objects
        """
        result = await db.execute(
            select(Message).where(Message.chat_id == chat_id)
        )
        return result.scalars().all()
    
    async def find_all(
        self,
        db: AsyncSession,
        skip: int = 0,
        limit: int = 100,
    ) -> Sequence[Message]:
        """Lists all message logs

        Args:
            db (AsyncSession): Database instance.
            skip (int, optional): Pagination start index.
            limit (int, optional): Pagination stop index.

        Returns:
            Sequence[Message]: A JSON array of all message logs
        """
        result = await db.execute(
            select(Message)
            .offset(skip)
            .limit(limit)
            .order_by(Message.created_at.desc())
        )
        return result.scalars().all()
