"""If the parent key is deleted, automatically delete the dependent foreign key record in other table

Revision ID: 35eaab4f3120
Revises: 546933a5a4fc
Create Date: 2025-12-04 18:02:58.010516

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '35eaab4f3120'
down_revision: Union[str, Sequence[str], None] = '546933a5a4fc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
