"""If the parent key is deleted, automatically delete the dependent foreign key record in other table

Revision ID: 546933a5a4fc
Revises: 6a8e512f8d2d
Create Date: 2025-12-04 17:57:58.998415

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '546933a5a4fc'
down_revision: Union[str, Sequence[str], None] = '6a8e512f8d2d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
