"""Created response mapper class in models for all routes to return a message and json

Revision ID: 6a8e512f8d2d
Revises: 9b7f377490f2
Create Date: 2025-12-04 16:34:06.623768

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '6a8e512f8d2d'
down_revision: Union[str, Sequence[str], None] = '9b7f377490f2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
