"""Initial migration

Revision ID: 75f6fcb75986
Revises: 
Create Date: 2025-12-04 12:26:28.359900

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '75f6fcb75986'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('company',
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('industry', sa.Enum('manufacturing', 'education', 'finance', 'construction', 'chemical', 'electronics', 'information_technology', name='industries'), nullable=False),
    sa.Column('location', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('website', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('company_id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('user',
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hashed_password', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('role', sa.Enum('job_seeker', 'recruiter', name='roles'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('jobseekers',
    sa.Column('first_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('last_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('desired_job_title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('job_seeker_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('phone_number', sa.Integer(), nullable=False),
    sa.Column('current_salary', sa.Integer(), nullable=False),
    sa.Column('location', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('job_seeker_id')
    )
    op.create_index(op.f('ix_jobseekers_user_id'), 'jobseekers', ['user_id'], unique=True)
    op.create_table('recruiters',
    sa.Column('first_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('last_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('recruiter_id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('phone_number', sa.Integer(), nullable=False),
    sa.Column('position', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['company.company_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('recruiter_id')
    )
    op.create_index(op.f('ix_recruiters_company_id'), 'recruiters', ['company_id'], unique=False)
    op.create_index(op.f('ix_recruiters_user_id'), 'recruiters', ['user_id'], unique=True)
    op.create_table('listings',
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('listing_id', sa.Integer(), nullable=False),
    sa.Column('recruiter_id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('posted_date', sa.Date(), nullable=False),
    sa.Column('location', sa.Enum('on_site', 'remote', 'hybrid', name='modes'), nullable=False),
    sa.Column('salary_range', sa.Enum('three_to_five', 'five_to_nine', 'nine_to_fifteen', 'fifteen_to_twentyTwo', name='salaries'), nullable=False),
    sa.Column('employment', sa.Enum('full_time', 'part_time', 'apprenticeship', 'internship', name='employment_type'), nullable=False),
    sa.Column('application_deadline', sa.Date(), nullable=False),
    sa.Column('is_active', sa.Enum('acceptance', 'expired', name='status_time'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['company.company_id'], ),
    sa.ForeignKeyConstraint(['recruiter_id'], ['recruiters.recruiter_id'], ),
    sa.PrimaryKeyConstraint('listing_id')
    )
    op.create_index(op.f('ix_listings_company_id'), 'listings', ['company_id'], unique=False)
    op.create_index(op.f('ix_listings_recruiter_id'), 'listings', ['recruiter_id'], unique=False)
    op.create_table('applications',
    sa.Column('application_id', sa.Integer(), nullable=False),
    sa.Column('listing_id', sa.Integer(), nullable=False),
    sa.Column('job_seeker_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'reviewed', 'accepted', 'rejected', name='application_status'), nullable=False),
    sa.Column('applied_date', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['job_seeker_id'], ['jobseekers.job_seeker_id'], ),
    sa.ForeignKeyConstraint(['listing_id'], ['listings.listing_id'], ),
    sa.PrimaryKeyConstraint('application_id')
    )
    op.create_index(op.f('ix_applications_job_seeker_id'), 'applications', ['job_seeker_id'], unique=False)
    op.create_index(op.f('ix_applications_listing_id'), 'applications', ['listing_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_applications_listing_id'), table_name='applications')
    op.drop_index(op.f('ix_applications_job_seeker_id'), table_name='applications')
    op.drop_table('applications')
    op.drop_index(op.f('ix_listings_recruiter_id'), table_name='listings')
    op.drop_index(op.f('ix_listings_company_id'), table_name='listings')
    op.drop_table('listings')
    op.drop_index(op.f('ix_recruiters_user_id'), table_name='recruiters')
    op.drop_index(op.f('ix_recruiters_company_id'), table_name='recruiters')
    op.drop_table('recruiters')
    op.drop_index(op.f('ix_jobseekers_user_id'), table_name='jobseekers')
    op.drop_table('jobseekers')
    op.drop_table('user')
    op.drop_table('company')
    # ### end Alembic commands ###
