"""Added role authenticated in user model

Revision ID: b8af2bd5349d
Revises: fcfa46eaad63
Create Date: 2025-12-09 18:01:14.949060

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b8af2bd5349d'
down_revision: Union[str, Sequence[str], None] = 'fcfa46eaad63'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
