"""Added class in Users model to read profile

Revision ID: babb6d191f9d
Revises: b8af2bd5349d
Create Date: 2025-12-25 12:52:25.676999

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'babb6d191f9d'
down_revision: Union[str, Sequence[str], None] = 'b8af2bd5349d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
