"""Re-generating tables due to Postgres server error

Revision ID: e994ee70898c
Revises: 35eaab4f3120
Create Date: 2025-12-08 16:12:39.118498

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e994ee70898c'
down_revision: Union[str, Sequence[str], None] = '35eaab4f3120'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
