"""Added past experience/skill set in job seeker

Revision ID: fcfa46eaad63
Revises: e994ee70898c
Create Date: 2025-12-08 19:01:19.518209

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = 'fcfa46eaad63'
down_revision: Union[str, Sequence[str], None] = 'e994ee70898c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobseekers', sa.Column('past_experience', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True))
    op.add_column('jobseekers', sa.Column('skill_set', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('jobseekers', 'skill_set')
    op.drop_column('jobseekers', 'past_experience')
    # ### end Alembic commands ###
